version: '3'

services: 

  #DB_Service
  db_service:
    container_name: database_container
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./db_data:/data/db
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mohamed012555557895
      MYSQL_DATABASE: blog_system
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  app:
    container_name: app_container
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db_service

  migration:
    container_name: migrator
    build: .
    depends_on:
      - db_service
    command: sh -c 'until nc -z db_service 3306; do sleep 1; done; npx sequelize-cli db:migrate'
